### ISSUE TITLE
Projects remain after deleted

### ISSUE THREAD

**Issue by ghost** [fabric-bolt/fabric-bolt#135]
Hi,
I don't find any information on this, but after deleting a project it goes away when selecting "All Projects" but stay on the left table where it says "Projects".
I don't know if it is a bug or something I'm missing.

**Comment by npardington** [comment]
Here's what I've done to try to reproduce the issue

1. I created a project

![screen shot 2015-08-21 at 8 14 08 am](https://cloud.githubusercontent.com/assets/2708258/9408020/bbae29f2-47dc-11e5-8b76-dd8e6cdad583.png)

2. Deleted project & I no longer see it listed under all projects or the left menu

![screen shot 2015-08-21 at 8 15 36 am](https://cloud.githubusercontent.com/assets/2708258/9408034/eaecf806-47dc-11e5-945d-bebd96f87f23.png)

Both places seem to be using the custom manager:

- https://github.com/fabric-bolt/fabric-bolt/blob/master/fabric_bolt/projects/views.py#L71
- https://github.com/fabric-bolt/fabric-bolt/blob/master/fabric_bolt/core/context_processors.py#L11

I will note that in the admin the projects will still show, but that's expected behavior.

Let me know if you're still seeing the issue and where & I'll take another look.
